project_name: psst

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/CanobbioE/please-safely-store-this/cmd.Version={{.Version}} -X github.com/CanobbioE/please-safely-store-this/cmd.Commit={{.Commit}} -X github.com/CanobbioE/please-safely-store-this/cmd.Date={{.Date}}
    main: ./main.go

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - docs/*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - 'README'
      - Merge pull request
      - Merge branch

brews:
  - tap:
      owner: "{{ .Env.GITHUB_USERNAME }}"
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/CanobbioE/please-safely-store-this"
    description: "A secure CLI password manager"
    license: "MIT"
    test: |
      system "#{bin}/psst --version"
    install: |
      bin.install "psst"

dockers:
  - image_templates:
      - "CanobbioE/please-safely-store-this:{{ .Version }}"
      - "CanobbioE/please-safely-store-this:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.Commit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
